name: Publish Logger NuGet Package

on:
  push:
    paths:
      - 'Abhiram.Abstractions.Logging/**'
    branches:
      - main
    workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and Publish Logger Package
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: Abhiram.Abstractions.Logging/Abhiram.Abstractions.Logging.csproj

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build
        run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore # This step is crucial!

      - name: Create NuGet packages
        run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --output ./nupkgs --no-build

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "https://nuget.pkg.github.com/Abhiram13/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate